### ISSUE TITLE
Illegal file name problem

### ISSUE THREAD

**Issue by kubapl2004gmail** [TheWilley/Fruity_Dance_Sprite_Sheet_Generator#28] opened 2023-03-25 12:48 UTC
Hi.
I tried to make bob-the-rapper skin for bfdance skin by TQualizer, but when I'm trying to save the spritesheet, the "Illegal file name" pops up. Please, fix this.
Sincerely, KubaPL2004 Studio's Grzymkowski.

**Comment by TheWilley** [comment] 2023-03-27 05:08
Hi! This pop up will show if your file name either contains a special character (such as `€%&!/` etc.) or if your file name is empty (i.e you've entered nothing into the filename section). Try to only use letters and number when naming your file, and it should work.

However, I do realise that the error message is very generic and actually does not tell you what the problem is with the file name. I will try to clarify this message to better explain the problem on a case by case basis (i.e the error message will change depending on the problem). This will be included in the next version.

**Comment by TheWilley** [comment] 2023-04-06 16:28
I realize that filenames are handled by the OS anyways, and thus checking the filename is redundant. I have decided to completely remove the option to give a filename in the app itself, as you can name it trough the download dialog box. Solved by 17409e26165bfc557ff7173ae3986f6370c6a951

**Closed by TheWilley** 2023-04-06 16:28 UTC
Labels: bug, Improvement
